  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - com.example::demo
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    DemoFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.funqy.lambda.FunqyStreamHandler::handleRequest
        Runtime: java8
        CodeUri: target/demo-1.0-SNAPSHOT-runner.jar
        MemorySize: 128
        Timeout: 15
        Policies: AWSLambdaBasicExecutionRole